WITH COUNTER_SALE AS (
    SELECT 
        PARTY_ID,
        CUSTOMER_NAME AS PARTY_NAME,
        NVL(SUM(TOTAL_AMOUNT),0) AS TOTAL_AMOUNT,
        MAX(ORDER_DATE) AS ORDER_DATE
    FROM
        TABLE(AB_SALE_ORDER_PKG.COUNTER_SALE_REPORT(:GV_ORG_ID, :GV_USER_ID))
    WHERE
           APPROVAL_STATUS = 'Approved' 
       AND PAYMENT_TYPE = 597
    GROUP BY
        PARTY_ID,
        CUSTOMER_NAME
),

COUNTER_SALE_RECOVERY AS (
    SELECT
        SO.CUSTOMER_ID AS PARTY_ID,
        SOD.SOD_DATE AS RECOVERY_DATE,
        NVL(SOD.TOTAL_AMOUNT,0) AS RECEIVED_AMOUNT
    FROM
        AB_SO_ORDER_HEAD SO
        JOIN AB_SO_ORDER_DET SOD 
            ON SOD.SO_ID = SO.SO_ID 
           AND SOD.STATUS = 'Y'
    WHERE
            SO.STATUS = 'Y'
        AND SO.SO_TYPE = '1007'
      --  AND SO.CUSTOMER_ID = :P135_PARTY_ID
)

SELECT
    PARTY_ID,
    PARTY_NAME,
    TRANS_DATE,
    RECOVERY_AMOUNT,
    RECEIVED_AMOUNT,
    SUM(RECOVERY_AMOUNT - RECEIVED_AMOUNT)
        OVER (ORDER BY TRANS_DATE
              ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) RUNNING_BALANCE
FROM
(
    SELECT
        CS.PARTY_ID,
        CS.PARTY_NAME,
        TO_DATE(CS.ORDER_DATE,'DD-MON-YYYY') AS TRANS_DATE,
        CS.TOTAL_AMOUNT AS RECOVERY_AMOUNT,
        0 AS RECEIVED_AMOUNT
    FROM COUNTER_SALE CS

    UNION ALL

    SELECT
        CSR.PARTY_ID,
        CS.PARTY_NAME,
       TO_DATE(TO_CHAR(CSR.RECOVERY_DATE,'DD-MON-YYYY'),'DD-MON-YYYY') AS TRANS_DATE,
        0 AS RECOVERY_AMOUNT,
        CSR.RECEIVED_AMOUNT
    FROM COUNTER_SALE_RECOVERY CSR
    JOIN COUNTER_SALE CS 
        ON CS.PARTY_ID = CSR.PARTY_ID
)

WHERE PARTY_ID = :P92_CUSTOMER_ID
ORDER BY TRANS_DATE;
