WITH COUNTER_SALE AS (
    SELECT 
        PARTY_ID,
        CUSTOMER_NAME AS PARTY_NAME,
        ORDER_DATE,
        SUM(NVL(TOTAL_AMOUNT,0)) AS TOTAL_AMOUNT 
    FROM
        TABLE(AB_SALE_ORDER_PKG.COUNTER_SALE_REPORT(:GV_ORG_ID, :GV_USER_ID))
    WHERE
           APPROVAL_STATUS = 'Approved' 
       AND PAYMENT_TYPE = 597
    GROUP BY
        PARTY_ID,
        CUSTOMER_NAME,
        ORDER_DATE 
),


COUNTER_SALE_RECOVERY AS (
    SELECT
        SO.CUSTOMER_ID AS PARTY_ID,
        SOD.SOD_DATE AS RECOVERY_DATE,
        SUM(NVL(SOD.TOTAL_AMOUNT,0)) AS RECEIVED_AMOUNT 
    FROM
        AB_SO_ORDER_HEAD SO
        JOIN AB_SO_ORDER_DET SOD 
            ON SOD.SO_ID = SO.SO_ID 
           AND SOD.STATUS = 'Y'
    WHERE
            SO.STATUS = 'Y'
        AND SO.SO_TYPE = '1007'
    GROUP BY
        SO.CUSTOMER_ID,
        SOD.SOD_DATE 
),


ALL_TRANSACTIONS AS (
   
    SELECT
        PARTY_ID,
        PARTY_NAME,
        ORDER_DATE AS TRANS_DATE, 
        TOTAL_AMOUNT AS RECOVERY_AMOUNT,
        0 AS RECEIVED_AMOUNT
    FROM COUNTER_SALE

    UNION ALL

 
    SELECT
        PARTY_ID,
        NULL AS PARTY_NAME, 
        RECOVERY_DATE AS TRANS_DATE, 
        0 AS RECOVERY_AMOUNT,
        RECEIVED_AMOUNT
    FROM COUNTER_SALE_RECOVERY
)


SELECT
    PARTY_ID,
   
    MAX(PARTY_NAME) OVER (PARTITION BY PARTY_ID) AS PARTY_NAME, 
    TRANS_DATE,
    RECOVERY_AMOUNT,
    RECEIVED_AMOUNT,
    SUM(RECOVERY_AMOUNT - RECEIVED_AMOUNT) 
        OVER (ORDER BY TRANS_DATE
              ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS RUNNING_BALANCE
FROM
    ALL_TRANSACTIONS
WHERE 
    PARTY_ID = :P92_CUSTOMER_ID
ORDER BY 
    TRANS_DATE


-- WITH COUNTER_SALE AS (
--     SELECT 
--         PARTY_ID,
--         CUSTOMER_NAME AS PARTY_NAME,
--         NVL(TOTAL_AMOUNT,0) AS TOTAL_AMOUNT,
--         ORDER_DATE AS ORDER_DATE
--     FROM
--         TABLE(AB_SALE_ORDER_PKG.COUNTER_SALE_REPORT(:GV_ORG_ID, :GV_USER_ID))
--     WHERE
--            APPROVAL_STATUS = 'Approved' 
--        AND PAYMENT_TYPE = 597
--     -- GROUP BY
--     --     PARTY_ID,
--     --     CUSTOMER_NAME, NVL(TOTAL_AMOUNT,0)
-- ),

-- COUNTER_SALE_RECOVERY AS (
--     SELECT
--         SO.CUSTOMER_ID AS PARTY_ID,
--         SOD.SOD_DATE AS RECOVERY_DATE,
--         NVL(SOD.TOTAL_AMOUNT,0) AS RECEIVED_AMOUNT
--     FROM
--         AB_SO_ORDER_HEAD SO
--         JOIN AB_SO_ORDER_DET SOD 
--             ON SOD.SO_ID = SO.SO_ID 
--            AND SOD.STATUS = 'Y'
--     WHERE
--             SO.STATUS = 'Y'
--         AND SO.SO_TYPE = '1007'
--       --  AND SO.CUSTOMER_ID = :P135_PARTY_ID
-- )

-- SELECT
-- DISTINCT
--     PARTY_ID,
--     PARTY_NAME,
--     TRANS_DATE,
--     RECOVERY_AMOUNT,
--     RECEIVED_AMOUNT,
--     SUM(RECOVERY_AMOUNT - RECEIVED_AMOUNT)
--         OVER (ORDER BY TRANS_DATE
--               ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) RUNNING_BALANCE
-- FROM
-- (
--     SELECT
--         CS.PARTY_ID,
--         CS.PARTY_NAME,
--          CS.ORDER_DATE AS TRANS_DATE, 
--         --TO_DATE(CS.ORDER_DATE,'DD-MON-YYYY') AS TRANS_DATE,
--         CS.TOTAL_AMOUNT AS RECOVERY_AMOUNT,
--         0 AS RECEIVED_AMOUNT
--     FROM COUNTER_SALE CS

--     UNION ALL

--     SELECT
--         CSR.PARTY_ID,
--         CS.PARTY_NAME,
--         CSR.RECOVERY_DATE AS TRANS_DATE, 
--       -- TO_DATE(TO_CHAR(CSR.RECOVERY_DATE,'DD-MON-YYYY'),'DD-MON-YYYY') AS TRANS_DATE,
--         0 AS RECOVERY_AMOUNT,
--         CSR.RECEIVED_AMOUNT
--     FROM COUNTER_SALE_RECOVERY CSR
--     JOIN COUNTER_SALE CS 
--         ON CS.PARTY_ID = CSR.PARTY_ID
-- )

-- WHERE PARTY_ID = :P92_CUSTOMER_ID
-- ORDER BY TRANS_DATE;
